# Generated by Django 5.2.17 on 2026-10-04 01:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('asset_class', models.CharField(choices=[('STOCKS', 'Stocks'), ('FOREX', 'Forex'), ('CRYPTO', 'Crypto'), ('FUTURES', 'Futures'), ('OPTIONS', 'Options')], max_length=10)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('entry_date', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fees', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='trades', to='journal.tag')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='journal.tradingaccount')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['status'], name='journal_tra_status_f21275_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['asset_class'], name='journal_tra_asset_c_066b16_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol'], name='journal_tra_symbol_53aab0_idx'),
        ),
    ]
